{% set version = "32.0.1" %}

package:
  name: pip-requirements-parser
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pip-requirements-parser/pip-requirements-parser-{{ version }}.tar.gz
  sha256: b4fa3a7a0be38243123cf9d1f3518da10c51bdb165a2b2985566247f9155a7d3

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=4
  run:
    - packaging
    - pyparsing
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - coverage
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - pip_requirements_parser
    - packaging_legacy_version
  commands:
    - pip check

about:
  home: https://github.com/nexB/pip-requirements-parser
  summary: pip requirements parser - a mostly correct pip requirements parsing library because it uses pip's own code.
  license: MIT
  license_file:
    - LICENSE
    # this is the pip license
    - mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
