{% set version = "32.0.1" %}
{% set cov = 89 %}
{% set cov = 84 %}  # [win]
{% set skips = "-k \"not skeleton_codestyle\"" %}
{% set skips = "-k \"not (to_dict or dumps_unparse or unexisting_path)\"" %}  # [win]

package:
  name: pip-requirements-parser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip-requirements-parser/pip-requirements-parser-{{ version }}.tar.gz
  sha256: b4fa3a7a0be38243123cf9d1f3518da10c51bdb165a2b2985566247f9155a7d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=4
  run:
    - packaging
    - pyparsing
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - pip_requirements_parser
    - packaging_legacy_version
  commands:
    - pip check
    - cd tests && pytest -vv --cov pip_requirements_parser --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under {{ cov }} {{ skips }}
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/nexB/pip-requirements-parser
  summary: pip requirements parser - a mostly correct pip requirements parsing library because it uses pip's own code.
  license: MIT
  license_file:
    - LICENSE
    # this is the pip license
    - mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
